# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Plain theme"
license = "MIT"
description = "Plain theme just for testing structure"
tags = ["website", "starter"]
features = ["posts"]
min_version = "0.64.0"

[author]
  name = "SG"
  homepage = "https://sg.com.mx"
